### ISSUE TITLE
em....How can I get rid of the voice of electicity.....

### ISSUE THREAD

**Issue by lacial** [mrcoles/javascript-piano#3]
when I press keys over two,the voice becomes strange.
I want to create a function to solve this problem.

**Comment by mrcoles** [comment]
Sounds fine to me on my apple laptop in google chrome. What type of browser and computer are you using? Also, is this something you wanted to work on?

**Comment by lacial** [comment]
Finally,I think it's the problem of my browser(Tecent browser).
I download the history version of chrome,and it runs perfectly.

**Comment by mrcoles** [comment]
OK 💃 

Ya, it can be a bit funny in different browsers.
