### ISSUE TITLE
Certain combinations of keys cause it not to execute...

### ISSUE THREAD

**Issue by jsphweid** [mrcoles/javascript-piano#4]
Thanks for this wonderfully simple project. I notice that chords work well, for example, playing "adg" or "sfg" work. Playing "hj;" however causes no notes to speak, for whatever reason.

Any idea what this could be related to?

**Comment by mrcoles** [comment]
In my experience it’s the keyboard or operating system and not the actual javascript code. I’ve had different levels of success with different configurations. You could see how a plugged in keyboard differs from perhaps a laptop keyboard? Or one on a different operating system?

Sorry, but I hope that helps in some way!
